name: Unit tests
on: [push]

jobs:
  build:
    name: Unit Tests node-${{ matrix.node_version }}, ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16, 17]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: test
        run: yarn test --ci
